remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [[bioconductor](https://new.bioconductor.org/)]
description: [记录学习[bioconductor](https://new.bioconductor.org/)单细胞测序工作流等。]
