project:
  type: book
  output-dir: docs

book:
  title: "Bioconductor_notes"
  reader-mode: true
  author: "王安林"
  date: "2023/12/20"
  chapters:
  
    - part: "Single-cell Analysis"
      chapters: 
        - index.qmd
        
        - intro.qmd
        - import.qmd
        - SCE.qmd
        - analysis.qmd
        
        - basics.qmd
        
    - part: "waiting"
    
  repo-url: https://github.com/Wanganlin00/Bioconductor_notes/
  repo-actions: [edit,issue]

execute:
  warning: false
  message: false
toc: true
toc-depth: 3
number-sections: true
number-offset: 2
knitr:
  opts_chunk: 
    comment: "#>" 
    collapse: TRUE
crossref: 
  fig-title: 图
  fig-prefix: 图
  
fig-width: 6
fig-asp: 0.618

format: 
  html: 
    theme: cosmo
    df-print: kable
    code-fold: true
    code-tools: true
    code-link: true
    html-math-method: katex
    callout-appearance: simple
    
editor: visual


